# ==============================
# БЛОК 1. ГЛОБАЛЬНЫЕ НАСТРОЙКИ PROMETHEUS
# ==============================

global:
  # Интервал сбора метрик.
  # Prometheus будет обращаться к приложению каждые 5 секунд.
  scrape_interval: 5s


# ==============================
# БЛОК 2. НАСТРОЙКА ИСТОЧНИКОВ МЕТРИК
# ==============================

scrape_configs:

  # Название задания сбора метрик.
  # В интерфейсе Prometheus метрики будут связаны с job_name = security_app.
  - job_name: 'security_app'

    # Статическая настройка источников метрик.
    # Используется, потому что адрес контейнера заранее известен.
    static_configs:

      # Цель сбора метрик.
      # security_app — имя контейнера приложения в docker-compose.yml.
      # 8000 — порт, на котором в main.py запущен Prometheus HTTP-сервер.
      - targets: ['security_app:8000']
